"""
Recommendation model for actionable trading recommendations.
"""
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Optional

from sqlalchemy import DateTime, ForeignKey, Index, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.card import Card
    from app.models.marketplace import Marketplace


class ActionType(str, Enum):
    """Recommendation action types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class Recommendation(Base):
    """
    Trading recommendation for a specific card.
    
    Generated by the recommendation agent based on analytics signals.
    """
    
    __tablename__ = "recommendations"
    
    # Foreign keys
    card_id: Mapped[int] = mapped_column(
        ForeignKey("cards.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    marketplace_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("marketplaces.id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    
    # Recommendation details
    action: Mapped[str] = mapped_column(String(10), nullable=False, index=True)
    
    # Confidence and timing
    confidence: Mapped[float] = mapped_column(Numeric(3, 2), nullable=False)
    horizon_days: Mapped[int] = mapped_column(default=7, nullable=False)
    
    # Price targets
    target_price: Mapped[Optional[float]] = mapped_column(Numeric(10, 2), nullable=True)
    current_price: Mapped[Optional[float]] = mapped_column(Numeric(10, 2), nullable=True)
    potential_profit_pct: Mapped[Optional[float]] = mapped_column(Numeric(5, 2), nullable=True)
    
    # Rationale
    rationale: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Source signals (JSON list of signal types)
    source_signals: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Validity
    valid_until: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)
    
    # Relationships
    card: Mapped["Card"] = relationship("Card", back_populates="recommendations")
    marketplace: Mapped[Optional["Marketplace"]] = relationship(
        "Marketplace", back_populates="recommendations"
    )
    
    # Indexes
    __table_args__ = (
        Index("ix_recommendations_card_action", "card_id", "action"),
        Index("ix_recommendations_action", "action"),
        Index("ix_recommendations_active", "is_active"),
        Index("ix_recommendations_confidence", "confidence"),
    )
    
    def __repr__(self) -> str:
        return f"<Recommendation {self.action} {self.card_id} (conf={self.confidence})>"

